theme = "rose_pine"

[editor]
auto-format = true

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true

[keys.normal]
"g" = { q = ":reflow 80" } 
space = {"x" = ":bc"}

[keys.insert] 
j = {k = "normal_mode"} 

